#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BELLA_17_09")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCONVENIADO(CONVENIADO instance);
    partial void UpdateCONVENIADO(CONVENIADO instance);
    partial void DeleteCONVENIADO(CONVENIADO instance);
    #endregion
		
		public DBDataContext() : 
				base(global::ConsoleApplication1.Properties.Settings.Default.BELLA_17_09ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CONVENIADO> CONVENIADOs
		{
			get
			{
				return this.GetTable<CONVENIADO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONVENIADOS")]
	public partial class CONVENIADO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CONV_ID;
		
		private System.Nullable<int> _EMPRES_ID;
		
		private System.Nullable<int> _BANCO;
		
		private int _GRUPO_CONV_EMP;
		
		private double _CHAPA;
		
		private string _SENHA;
		
		private string _TITULAR;
		
		private System.Nullable<int> _CONTRATO;
		
		private decimal _LIMITE_MES;
		
		private char _LIBERADO;
		
		private char _FIDELIDADE;
		
		private char _APAGADO;
		
		private System.Nullable<System.DateTime> _DT_NASCIMENTO;
		
		private string _CARGO;
		
		private string _SETOR;
		
		private string _CPF;
		
		private string _RG;
		
		private System.Nullable<decimal> _LIMITE_TOTAL;
		
		private System.Nullable<decimal> _LIMITE_PROX_FECHAMENTO;
		
		private string _AGENCIA;
		
		private string _CONTACORRENTE;
		
		private string _DIGITO_CONTA;
		
		private System.Nullable<char> _TIPOPAGAMENTO;
		
		private string _ENDERECO;
		
		private System.Nullable<int> _NUMERO;
		
		private string _BAIRRO;
		
		private string _CIDADE;
		
		private string _ESTADO;
		
		private string _CEP;
		
		private string _TELEFONE1;
		
		private string _TELEFONE2;
		
		private string _CELULAR;
		
		private string _OBS1;
		
		private string _OBS2;
		
		private string _EMAIL;
		
		private System.Nullable<decimal> _CESTABASICA;
		
		private System.Nullable<System.DateTime> _DTULTCESTA;
		
		private System.Nullable<decimal> _SALARIO;
		
		private string _TIPOSALARIO;
		
		private string _COD_EMPRESA;
		
		private System.Nullable<char> _FLAG;
		
		private System.Nullable<System.DateTime> _DTASSOCIACAO;
		
		private System.Nullable<System.DateTime> _DTAPAGADO;
		
		private System.Nullable<System.DateTime> _DTALTERACAO;
		
		private string _OPERADOR;
		
		private System.Nullable<System.DateTime> _DTCADASTRO;
		
		private string _OPERCADASTRO;
		
		private System.Nullable<char> _VALE_DESCONTO;
		
		private System.Nullable<char> _LIBERA_GRUPOSPROD;
		
		private string _COMPLEMENTO;
		
		private System.Nullable<char> _USA_SALDO_DIF;
		
		private System.Nullable<decimal> _ABONO_MES;
		
		private System.Nullable<decimal> _SALDO_RENOVACAO;
		
		private System.Nullable<decimal> _SALDO_ACUMULADO;
		
		private System.Nullable<System.DateTime> _DATA_ATUALIZACAO_ACUMULADO;
		
		private System.Nullable<decimal> _CONSUMO_MES_1;
		
		private System.Nullable<decimal> _CONSUMO_MES_2;
		
		private System.Nullable<decimal> _CONSUMO_MES_3;
		
		private System.Nullable<decimal> _CONSUMO_MES_4;
		
		private System.Nullable<float> _PIS;
		
		private string _NOME_PAI;
		
		private string _nome_mae;
		
		private System.Nullable<int> _CART_TRAB_NUM;
		
		private string _CART_TRAB_SERIE;
		
		private string _REGIME_TRAB;
		
		private System.Nullable<decimal> _VENC_TOTAL;
		
		private string _ESTADO_CIVIL;
		
		private System.Nullable<int> _NUM_DEPENDENTES;
		
		private System.Nullable<System.DateTime> _DATA_ADMISSAO;
		
		private System.Nullable<System.DateTime> _DATA_DEMISSAO;
		
		private System.Nullable<System.DateTime> _FIM_CONTRATO;
		
		private string _DISTRITO;
		
		private System.Nullable<decimal> _SALDO_DEVEDOR;
		
		private System.Nullable<decimal> _SALDO_DEVEDOR_FAT;
		
		private System.Nullable<int> _SETOR_ID;
		
		private char _CARTAO_BEM_ESTAR;
		
		private System.Nullable<char> _ENVIA_SMS;
		
		private System.Nullable<char> _NAO_GERA_CARTAO_TITULAR;
		
		private System.Nullable<char> _TAXA_SERVICO_CANTINA;
		
		private string _SENHA_CANTINEX;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCONV_IDChanging(int value);
    partial void OnCONV_IDChanged();
    partial void OnEMPRES_IDChanging(System.Nullable<int> value);
    partial void OnEMPRES_IDChanged();
    partial void OnBANCOChanging(System.Nullable<int> value);
    partial void OnBANCOChanged();
    partial void OnGRUPO_CONV_EMPChanging(int value);
    partial void OnGRUPO_CONV_EMPChanged();
    partial void OnCHAPAChanging(double value);
    partial void OnCHAPAChanged();
    partial void OnSENHAChanging(string value);
    partial void OnSENHAChanged();
    partial void OnTITULARChanging(string value);
    partial void OnTITULARChanged();
    partial void OnCONTRATOChanging(System.Nullable<int> value);
    partial void OnCONTRATOChanged();
    partial void OnLIMITE_MESChanging(decimal value);
    partial void OnLIMITE_MESChanged();
    partial void OnLIBERADOChanging(char value);
    partial void OnLIBERADOChanged();
    partial void OnFIDELIDADEChanging(char value);
    partial void OnFIDELIDADEChanged();
    partial void OnAPAGADOChanging(char value);
    partial void OnAPAGADOChanged();
    partial void OnDT_NASCIMENTOChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_NASCIMENTOChanged();
    partial void OnCARGOChanging(string value);
    partial void OnCARGOChanged();
    partial void OnSETORChanging(string value);
    partial void OnSETORChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnRGChanging(string value);
    partial void OnRGChanged();
    partial void OnLIMITE_TOTALChanging(System.Nullable<decimal> value);
    partial void OnLIMITE_TOTALChanged();
    partial void OnLIMITE_PROX_FECHAMENTOChanging(System.Nullable<decimal> value);
    partial void OnLIMITE_PROX_FECHAMENTOChanged();
    partial void OnAGENCIAChanging(string value);
    partial void OnAGENCIAChanged();
    partial void OnCONTACORRENTEChanging(string value);
    partial void OnCONTACORRENTEChanged();
    partial void OnDIGITO_CONTAChanging(string value);
    partial void OnDIGITO_CONTAChanged();
    partial void OnTIPOPAGAMENTOChanging(System.Nullable<char> value);
    partial void OnTIPOPAGAMENTOChanged();
    partial void OnENDERECOChanging(string value);
    partial void OnENDERECOChanged();
    partial void OnNUMEROChanging(System.Nullable<int> value);
    partial void OnNUMEROChanged();
    partial void OnBAIRROChanging(string value);
    partial void OnBAIRROChanged();
    partial void OnCIDADEChanging(string value);
    partial void OnCIDADEChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnTELEFONE1Changing(string value);
    partial void OnTELEFONE1Changed();
    partial void OnTELEFONE2Changing(string value);
    partial void OnTELEFONE2Changed();
    partial void OnCELULARChanging(string value);
    partial void OnCELULARChanged();
    partial void OnOBS1Changing(string value);
    partial void OnOBS1Changed();
    partial void OnOBS2Changing(string value);
    partial void OnOBS2Changed();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnCESTABASICAChanging(System.Nullable<decimal> value);
    partial void OnCESTABASICAChanged();
    partial void OnDTULTCESTAChanging(System.Nullable<System.DateTime> value);
    partial void OnDTULTCESTAChanged();
    partial void OnSALARIOChanging(System.Nullable<decimal> value);
    partial void OnSALARIOChanged();
    partial void OnTIPOSALARIOChanging(string value);
    partial void OnTIPOSALARIOChanged();
    partial void OnCOD_EMPRESAChanging(string value);
    partial void OnCOD_EMPRESAChanged();
    partial void OnFLAGChanging(System.Nullable<char> value);
    partial void OnFLAGChanged();
    partial void OnDTASSOCIACAOChanging(System.Nullable<System.DateTime> value);
    partial void OnDTASSOCIACAOChanged();
    partial void OnDTAPAGADOChanging(System.Nullable<System.DateTime> value);
    partial void OnDTAPAGADOChanged();
    partial void OnDTALTERACAOChanging(System.Nullable<System.DateTime> value);
    partial void OnDTALTERACAOChanged();
    partial void OnOPERADORChanging(string value);
    partial void OnOPERADORChanged();
    partial void OnDTCADASTROChanging(System.Nullable<System.DateTime> value);
    partial void OnDTCADASTROChanged();
    partial void OnOPERCADASTROChanging(string value);
    partial void OnOPERCADASTROChanged();
    partial void OnVALE_DESCONTOChanging(System.Nullable<char> value);
    partial void OnVALE_DESCONTOChanged();
    partial void OnLIBERA_GRUPOSPRODChanging(System.Nullable<char> value);
    partial void OnLIBERA_GRUPOSPRODChanged();
    partial void OnCOMPLEMENTOChanging(string value);
    partial void OnCOMPLEMENTOChanged();
    partial void OnUSA_SALDO_DIFChanging(System.Nullable<char> value);
    partial void OnUSA_SALDO_DIFChanged();
    partial void OnABONO_MESChanging(System.Nullable<decimal> value);
    partial void OnABONO_MESChanged();
    partial void OnSALDO_RENOVACAOChanging(System.Nullable<decimal> value);
    partial void OnSALDO_RENOVACAOChanged();
    partial void OnSALDO_ACUMULADOChanging(System.Nullable<decimal> value);
    partial void OnSALDO_ACUMULADOChanged();
    partial void OnDATA_ATUALIZACAO_ACUMULADOChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_ATUALIZACAO_ACUMULADOChanged();
    partial void OnCONSUMO_MES_1Changing(System.Nullable<decimal> value);
    partial void OnCONSUMO_MES_1Changed();
    partial void OnCONSUMO_MES_2Changing(System.Nullable<decimal> value);
    partial void OnCONSUMO_MES_2Changed();
    partial void OnCONSUMO_MES_3Changing(System.Nullable<decimal> value);
    partial void OnCONSUMO_MES_3Changed();
    partial void OnCONSUMO_MES_4Changing(System.Nullable<decimal> value);
    partial void OnCONSUMO_MES_4Changed();
    partial void OnPISChanging(System.Nullable<float> value);
    partial void OnPISChanged();
    partial void OnNOME_PAIChanging(string value);
    partial void OnNOME_PAIChanged();
    partial void Onnome_maeChanging(string value);
    partial void Onnome_maeChanged();
    partial void OnCART_TRAB_NUMChanging(System.Nullable<int> value);
    partial void OnCART_TRAB_NUMChanged();
    partial void OnCART_TRAB_SERIEChanging(string value);
    partial void OnCART_TRAB_SERIEChanged();
    partial void OnREGIME_TRABChanging(string value);
    partial void OnREGIME_TRABChanged();
    partial void OnVENC_TOTALChanging(System.Nullable<decimal> value);
    partial void OnVENC_TOTALChanged();
    partial void OnESTADO_CIVILChanging(string value);
    partial void OnESTADO_CIVILChanged();
    partial void OnNUM_DEPENDENTESChanging(System.Nullable<int> value);
    partial void OnNUM_DEPENDENTESChanged();
    partial void OnDATA_ADMISSAOChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_ADMISSAOChanged();
    partial void OnDATA_DEMISSAOChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_DEMISSAOChanged();
    partial void OnFIM_CONTRATOChanging(System.Nullable<System.DateTime> value);
    partial void OnFIM_CONTRATOChanged();
    partial void OnDISTRITOChanging(string value);
    partial void OnDISTRITOChanged();
    partial void OnSALDO_DEVEDORChanging(System.Nullable<decimal> value);
    partial void OnSALDO_DEVEDORChanged();
    partial void OnSALDO_DEVEDOR_FATChanging(System.Nullable<decimal> value);
    partial void OnSALDO_DEVEDOR_FATChanged();
    partial void OnSETOR_IDChanging(System.Nullable<int> value);
    partial void OnSETOR_IDChanged();
    partial void OnCARTAO_BEM_ESTARChanging(char value);
    partial void OnCARTAO_BEM_ESTARChanged();
    partial void OnENVIA_SMSChanging(System.Nullable<char> value);
    partial void OnENVIA_SMSChanged();
    partial void OnNAO_GERA_CARTAO_TITULARChanging(System.Nullable<char> value);
    partial void OnNAO_GERA_CARTAO_TITULARChanged();
    partial void OnTAXA_SERVICO_CANTINAChanging(System.Nullable<char> value);
    partial void OnTAXA_SERVICO_CANTINAChanged();
    partial void OnSENHA_CANTINEXChanging(string value);
    partial void OnSENHA_CANTINEXChanged();
    #endregion
		
		public CONVENIADO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONV_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CONV_ID
		{
			get
			{
				return this._CONV_ID;
			}
			set
			{
				if ((this._CONV_ID != value))
				{
					this.OnCONV_IDChanging(value);
					this.SendPropertyChanging();
					this._CONV_ID = value;
					this.SendPropertyChanged("CONV_ID");
					this.OnCONV_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPRES_ID", DbType="Int")]
		public System.Nullable<int> EMPRES_ID
		{
			get
			{
				return this._EMPRES_ID;
			}
			set
			{
				if ((this._EMPRES_ID != value))
				{
					this.OnEMPRES_IDChanging(value);
					this.SendPropertyChanging();
					this._EMPRES_ID = value;
					this.SendPropertyChanged("EMPRES_ID");
					this.OnEMPRES_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANCO", DbType="Int")]
		public System.Nullable<int> BANCO
		{
			get
			{
				return this._BANCO;
			}
			set
			{
				if ((this._BANCO != value))
				{
					this.OnBANCOChanging(value);
					this.SendPropertyChanging();
					this._BANCO = value;
					this.SendPropertyChanged("BANCO");
					this.OnBANCOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPO_CONV_EMP", DbType="Int NOT NULL")]
		public int GRUPO_CONV_EMP
		{
			get
			{
				return this._GRUPO_CONV_EMP;
			}
			set
			{
				if ((this._GRUPO_CONV_EMP != value))
				{
					this.OnGRUPO_CONV_EMPChanging(value);
					this.SendPropertyChanging();
					this._GRUPO_CONV_EMP = value;
					this.SendPropertyChanged("GRUPO_CONV_EMP");
					this.OnGRUPO_CONV_EMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAPA", DbType="Float NOT NULL")]
		public double CHAPA
		{
			get
			{
				return this._CHAPA;
			}
			set
			{
				if ((this._CHAPA != value))
				{
					this.OnCHAPAChanging(value);
					this.SendPropertyChanging();
					this._CHAPA = value;
					this.SendPropertyChanged("CHAPA");
					this.OnCHAPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SENHA", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string SENHA
		{
			get
			{
				return this._SENHA;
			}
			set
			{
				if ((this._SENHA != value))
				{
					this.OnSENHAChanging(value);
					this.SendPropertyChanging();
					this._SENHA = value;
					this.SendPropertyChanged("SENHA");
					this.OnSENHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULAR", DbType="VarChar(58) NOT NULL", CanBeNull=false)]
		public string TITULAR
		{
			get
			{
				return this._TITULAR;
			}
			set
			{
				if ((this._TITULAR != value))
				{
					this.OnTITULARChanging(value);
					this.SendPropertyChanging();
					this._TITULAR = value;
					this.SendPropertyChanged("TITULAR");
					this.OnTITULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRATO", DbType="Int")]
		public System.Nullable<int> CONTRATO
		{
			get
			{
				return this._CONTRATO;
			}
			set
			{
				if ((this._CONTRATO != value))
				{
					this.OnCONTRATOChanging(value);
					this.SendPropertyChanging();
					this._CONTRATO = value;
					this.SendPropertyChanged("CONTRATO");
					this.OnCONTRATOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIMITE_MES", DbType="Decimal(15,2) NOT NULL")]
		public decimal LIMITE_MES
		{
			get
			{
				return this._LIMITE_MES;
			}
			set
			{
				if ((this._LIMITE_MES != value))
				{
					this.OnLIMITE_MESChanging(value);
					this.SendPropertyChanging();
					this._LIMITE_MES = value;
					this.SendPropertyChanged("LIMITE_MES");
					this.OnLIMITE_MESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIBERADO", DbType="Char(1) NOT NULL")]
		public char LIBERADO
		{
			get
			{
				return this._LIBERADO;
			}
			set
			{
				if ((this._LIBERADO != value))
				{
					this.OnLIBERADOChanging(value);
					this.SendPropertyChanging();
					this._LIBERADO = value;
					this.SendPropertyChanged("LIBERADO");
					this.OnLIBERADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIDELIDADE", DbType="Char(1) NOT NULL")]
		public char FIDELIDADE
		{
			get
			{
				return this._FIDELIDADE;
			}
			set
			{
				if ((this._FIDELIDADE != value))
				{
					this.OnFIDELIDADEChanging(value);
					this.SendPropertyChanging();
					this._FIDELIDADE = value;
					this.SendPropertyChanged("FIDELIDADE");
					this.OnFIDELIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APAGADO", DbType="Char(1) NOT NULL")]
		public char APAGADO
		{
			get
			{
				return this._APAGADO;
			}
			set
			{
				if ((this._APAGADO != value))
				{
					this.OnAPAGADOChanging(value);
					this.SendPropertyChanging();
					this._APAGADO = value;
					this.SendPropertyChanged("APAGADO");
					this.OnAPAGADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_NASCIMENTO", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DT_NASCIMENTO
		{
			get
			{
				return this._DT_NASCIMENTO;
			}
			set
			{
				if ((this._DT_NASCIMENTO != value))
				{
					this.OnDT_NASCIMENTOChanging(value);
					this.SendPropertyChanging();
					this._DT_NASCIMENTO = value;
					this.SendPropertyChanged("DT_NASCIMENTO");
					this.OnDT_NASCIMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARGO", DbType="VarChar(45)")]
		public string CARGO
		{
			get
			{
				return this._CARGO;
			}
			set
			{
				if ((this._CARGO != value))
				{
					this.OnCARGOChanging(value);
					this.SendPropertyChanging();
					this._CARGO = value;
					this.SendPropertyChanged("CARGO");
					this.OnCARGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SETOR", DbType="VarChar(45)")]
		public string SETOR
		{
			get
			{
				return this._SETOR;
			}
			set
			{
				if ((this._SETOR != value))
				{
					this.OnSETORChanging(value);
					this.SendPropertyChanging();
					this._SETOR = value;
					this.SendPropertyChanged("SETOR");
					this.OnSETORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(14)")]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG", DbType="VarChar(13)")]
		public string RG
		{
			get
			{
				return this._RG;
			}
			set
			{
				if ((this._RG != value))
				{
					this.OnRGChanging(value);
					this.SendPropertyChanging();
					this._RG = value;
					this.SendPropertyChanged("RG");
					this.OnRGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIMITE_TOTAL", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> LIMITE_TOTAL
		{
			get
			{
				return this._LIMITE_TOTAL;
			}
			set
			{
				if ((this._LIMITE_TOTAL != value))
				{
					this.OnLIMITE_TOTALChanging(value);
					this.SendPropertyChanging();
					this._LIMITE_TOTAL = value;
					this.SendPropertyChanged("LIMITE_TOTAL");
					this.OnLIMITE_TOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIMITE_PROX_FECHAMENTO", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> LIMITE_PROX_FECHAMENTO
		{
			get
			{
				return this._LIMITE_PROX_FECHAMENTO;
			}
			set
			{
				if ((this._LIMITE_PROX_FECHAMENTO != value))
				{
					this.OnLIMITE_PROX_FECHAMENTOChanging(value);
					this.SendPropertyChanging();
					this._LIMITE_PROX_FECHAMENTO = value;
					this.SendPropertyChanged("LIMITE_PROX_FECHAMENTO");
					this.OnLIMITE_PROX_FECHAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENCIA", DbType="VarChar(7)")]
		public string AGENCIA
		{
			get
			{
				return this._AGENCIA;
			}
			set
			{
				if ((this._AGENCIA != value))
				{
					this.OnAGENCIAChanging(value);
					this.SendPropertyChanging();
					this._AGENCIA = value;
					this.SendPropertyChanged("AGENCIA");
					this.OnAGENCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACORRENTE", DbType="VarChar(10)")]
		public string CONTACORRENTE
		{
			get
			{
				return this._CONTACORRENTE;
			}
			set
			{
				if ((this._CONTACORRENTE != value))
				{
					this.OnCONTACORRENTEChanging(value);
					this.SendPropertyChanging();
					this._CONTACORRENTE = value;
					this.SendPropertyChanged("CONTACORRENTE");
					this.OnCONTACORRENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIGITO_CONTA", DbType="VarChar(2)")]
		public string DIGITO_CONTA
		{
			get
			{
				return this._DIGITO_CONTA;
			}
			set
			{
				if ((this._DIGITO_CONTA != value))
				{
					this.OnDIGITO_CONTAChanging(value);
					this.SendPropertyChanging();
					this._DIGITO_CONTA = value;
					this.SendPropertyChanged("DIGITO_CONTA");
					this.OnDIGITO_CONTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPOPAGAMENTO", DbType="Char(1)")]
		public System.Nullable<char> TIPOPAGAMENTO
		{
			get
			{
				return this._TIPOPAGAMENTO;
			}
			set
			{
				if ((this._TIPOPAGAMENTO != value))
				{
					this.OnTIPOPAGAMENTOChanging(value);
					this.SendPropertyChanging();
					this._TIPOPAGAMENTO = value;
					this.SendPropertyChanged("TIPOPAGAMENTO");
					this.OnTIPOPAGAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDERECO", DbType="VarChar(60)")]
		public string ENDERECO
		{
			get
			{
				return this._ENDERECO;
			}
			set
			{
				if ((this._ENDERECO != value))
				{
					this.OnENDERECOChanging(value);
					this.SendPropertyChanging();
					this._ENDERECO = value;
					this.SendPropertyChanged("ENDERECO");
					this.OnENDERECOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO", DbType="Int")]
		public System.Nullable<int> NUMERO
		{
			get
			{
				return this._NUMERO;
			}
			set
			{
				if ((this._NUMERO != value))
				{
					this.OnNUMEROChanging(value);
					this.SendPropertyChanging();
					this._NUMERO = value;
					this.SendPropertyChanged("NUMERO");
					this.OnNUMEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAIRRO", DbType="VarChar(30)")]
		public string BAIRRO
		{
			get
			{
				return this._BAIRRO;
			}
			set
			{
				if ((this._BAIRRO != value))
				{
					this.OnBAIRROChanging(value);
					this.SendPropertyChanging();
					this._BAIRRO = value;
					this.SendPropertyChanged("BAIRRO");
					this.OnBAIRROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIDADE", DbType="VarChar(30)")]
		public string CIDADE
		{
			get
			{
				return this._CIDADE;
			}
			set
			{
				if ((this._CIDADE != value))
				{
					this.OnCIDADEChanging(value);
					this.SendPropertyChanging();
					this._CIDADE = value;
					this.SendPropertyChanged("CIDADE");
					this.OnCIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Char(2)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(9)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONE1", DbType="VarChar(14)")]
		public string TELEFONE1
		{
			get
			{
				return this._TELEFONE1;
			}
			set
			{
				if ((this._TELEFONE1 != value))
				{
					this.OnTELEFONE1Changing(value);
					this.SendPropertyChanging();
					this._TELEFONE1 = value;
					this.SendPropertyChanged("TELEFONE1");
					this.OnTELEFONE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONE2", DbType="VarChar(14)")]
		public string TELEFONE2
		{
			get
			{
				return this._TELEFONE2;
			}
			set
			{
				if ((this._TELEFONE2 != value))
				{
					this.OnTELEFONE2Changing(value);
					this.SendPropertyChanging();
					this._TELEFONE2 = value;
					this.SendPropertyChanged("TELEFONE2");
					this.OnTELEFONE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELULAR", DbType="VarChar(14)")]
		public string CELULAR
		{
			get
			{
				return this._CELULAR;
			}
			set
			{
				if ((this._CELULAR != value))
				{
					this.OnCELULARChanging(value);
					this.SendPropertyChanging();
					this._CELULAR = value;
					this.SendPropertyChanged("CELULAR");
					this.OnCELULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBS1", DbType="VarChar(80)")]
		public string OBS1
		{
			get
			{
				return this._OBS1;
			}
			set
			{
				if ((this._OBS1 != value))
				{
					this.OnOBS1Changing(value);
					this.SendPropertyChanging();
					this._OBS1 = value;
					this.SendPropertyChanged("OBS1");
					this.OnOBS1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBS2", DbType="VarChar(80)")]
		public string OBS2
		{
			get
			{
				return this._OBS2;
			}
			set
			{
				if ((this._OBS2 != value))
				{
					this.OnOBS2Changing(value);
					this.SendPropertyChanging();
					this._OBS2 = value;
					this.SendPropertyChanged("OBS2");
					this.OnOBS2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CESTABASICA", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> CESTABASICA
		{
			get
			{
				return this._CESTABASICA;
			}
			set
			{
				if ((this._CESTABASICA != value))
				{
					this.OnCESTABASICAChanging(value);
					this.SendPropertyChanging();
					this._CESTABASICA = value;
					this.SendPropertyChanged("CESTABASICA");
					this.OnCESTABASICAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTULTCESTA", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DTULTCESTA
		{
			get
			{
				return this._DTULTCESTA;
			}
			set
			{
				if ((this._DTULTCESTA != value))
				{
					this.OnDTULTCESTAChanging(value);
					this.SendPropertyChanging();
					this._DTULTCESTA = value;
					this.SendPropertyChanged("DTULTCESTA");
					this.OnDTULTCESTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALARIO", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> SALARIO
		{
			get
			{
				return this._SALARIO;
			}
			set
			{
				if ((this._SALARIO != value))
				{
					this.OnSALARIOChanging(value);
					this.SendPropertyChanging();
					this._SALARIO = value;
					this.SendPropertyChanged("SALARIO");
					this.OnSALARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPOSALARIO", DbType="VarChar(15)")]
		public string TIPOSALARIO
		{
			get
			{
				return this._TIPOSALARIO;
			}
			set
			{
				if ((this._TIPOSALARIO != value))
				{
					this.OnTIPOSALARIOChanging(value);
					this.SendPropertyChanging();
					this._TIPOSALARIO = value;
					this.SendPropertyChanged("TIPOSALARIO");
					this.OnTIPOSALARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_EMPRESA", DbType="VarChar(30)")]
		public string COD_EMPRESA
		{
			get
			{
				return this._COD_EMPRESA;
			}
			set
			{
				if ((this._COD_EMPRESA != value))
				{
					this.OnCOD_EMPRESAChanging(value);
					this.SendPropertyChanging();
					this._COD_EMPRESA = value;
					this.SendPropertyChanged("COD_EMPRESA");
					this.OnCOD_EMPRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Char(1)")]
		public System.Nullable<char> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTASSOCIACAO", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DTASSOCIACAO
		{
			get
			{
				return this._DTASSOCIACAO;
			}
			set
			{
				if ((this._DTASSOCIACAO != value))
				{
					this.OnDTASSOCIACAOChanging(value);
					this.SendPropertyChanging();
					this._DTASSOCIACAO = value;
					this.SendPropertyChanged("DTASSOCIACAO");
					this.OnDTASSOCIACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTAPAGADO", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DTAPAGADO
		{
			get
			{
				return this._DTAPAGADO;
			}
			set
			{
				if ((this._DTAPAGADO != value))
				{
					this.OnDTAPAGADOChanging(value);
					this.SendPropertyChanging();
					this._DTAPAGADO = value;
					this.SendPropertyChanged("DTAPAGADO");
					this.OnDTAPAGADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTALTERACAO", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DTALTERACAO
		{
			get
			{
				return this._DTALTERACAO;
			}
			set
			{
				if ((this._DTALTERACAO != value))
				{
					this.OnDTALTERACAOChanging(value);
					this.SendPropertyChanging();
					this._DTALTERACAO = value;
					this.SendPropertyChanged("DTALTERACAO");
					this.OnDTALTERACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERADOR", DbType="VarChar(25)")]
		public string OPERADOR
		{
			get
			{
				return this._OPERADOR;
			}
			set
			{
				if ((this._OPERADOR != value))
				{
					this.OnOPERADORChanging(value);
					this.SendPropertyChanging();
					this._OPERADOR = value;
					this.SendPropertyChanged("OPERADOR");
					this.OnOPERADORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTCADASTRO", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DTCADASTRO
		{
			get
			{
				return this._DTCADASTRO;
			}
			set
			{
				if ((this._DTCADASTRO != value))
				{
					this.OnDTCADASTROChanging(value);
					this.SendPropertyChanging();
					this._DTCADASTRO = value;
					this.SendPropertyChanged("DTCADASTRO");
					this.OnDTCADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERCADASTRO", DbType="VarChar(25)")]
		public string OPERCADASTRO
		{
			get
			{
				return this._OPERCADASTRO;
			}
			set
			{
				if ((this._OPERCADASTRO != value))
				{
					this.OnOPERCADASTROChanging(value);
					this.SendPropertyChanging();
					this._OPERCADASTRO = value;
					this.SendPropertyChanged("OPERCADASTRO");
					this.OnOPERCADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALE_DESCONTO", DbType="Char(1)")]
		public System.Nullable<char> VALE_DESCONTO
		{
			get
			{
				return this._VALE_DESCONTO;
			}
			set
			{
				if ((this._VALE_DESCONTO != value))
				{
					this.OnVALE_DESCONTOChanging(value);
					this.SendPropertyChanging();
					this._VALE_DESCONTO = value;
					this.SendPropertyChanged("VALE_DESCONTO");
					this.OnVALE_DESCONTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIBERA_GRUPOSPROD", DbType="Char(1)")]
		public System.Nullable<char> LIBERA_GRUPOSPROD
		{
			get
			{
				return this._LIBERA_GRUPOSPROD;
			}
			set
			{
				if ((this._LIBERA_GRUPOSPROD != value))
				{
					this.OnLIBERA_GRUPOSPRODChanging(value);
					this.SendPropertyChanging();
					this._LIBERA_GRUPOSPROD = value;
					this.SendPropertyChanged("LIBERA_GRUPOSPROD");
					this.OnLIBERA_GRUPOSPRODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPLEMENTO", DbType="VarChar(30)")]
		public string COMPLEMENTO
		{
			get
			{
				return this._COMPLEMENTO;
			}
			set
			{
				if ((this._COMPLEMENTO != value))
				{
					this.OnCOMPLEMENTOChanging(value);
					this.SendPropertyChanging();
					this._COMPLEMENTO = value;
					this.SendPropertyChanged("COMPLEMENTO");
					this.OnCOMPLEMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USA_SALDO_DIF", DbType="Char(1)")]
		public System.Nullable<char> USA_SALDO_DIF
		{
			get
			{
				return this._USA_SALDO_DIF;
			}
			set
			{
				if ((this._USA_SALDO_DIF != value))
				{
					this.OnUSA_SALDO_DIFChanging(value);
					this.SendPropertyChanging();
					this._USA_SALDO_DIF = value;
					this.SendPropertyChanged("USA_SALDO_DIF");
					this.OnUSA_SALDO_DIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABONO_MES", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> ABONO_MES
		{
			get
			{
				return this._ABONO_MES;
			}
			set
			{
				if ((this._ABONO_MES != value))
				{
					this.OnABONO_MESChanging(value);
					this.SendPropertyChanging();
					this._ABONO_MES = value;
					this.SendPropertyChanged("ABONO_MES");
					this.OnABONO_MESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALDO_RENOVACAO", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> SALDO_RENOVACAO
		{
			get
			{
				return this._SALDO_RENOVACAO;
			}
			set
			{
				if ((this._SALDO_RENOVACAO != value))
				{
					this.OnSALDO_RENOVACAOChanging(value);
					this.SendPropertyChanging();
					this._SALDO_RENOVACAO = value;
					this.SendPropertyChanged("SALDO_RENOVACAO");
					this.OnSALDO_RENOVACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALDO_ACUMULADO", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> SALDO_ACUMULADO
		{
			get
			{
				return this._SALDO_ACUMULADO;
			}
			set
			{
				if ((this._SALDO_ACUMULADO != value))
				{
					this.OnSALDO_ACUMULADOChanging(value);
					this.SendPropertyChanging();
					this._SALDO_ACUMULADO = value;
					this.SendPropertyChanged("SALDO_ACUMULADO");
					this.OnSALDO_ACUMULADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_ATUALIZACAO_ACUMULADO", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DATA_ATUALIZACAO_ACUMULADO
		{
			get
			{
				return this._DATA_ATUALIZACAO_ACUMULADO;
			}
			set
			{
				if ((this._DATA_ATUALIZACAO_ACUMULADO != value))
				{
					this.OnDATA_ATUALIZACAO_ACUMULADOChanging(value);
					this.SendPropertyChanging();
					this._DATA_ATUALIZACAO_ACUMULADO = value;
					this.SendPropertyChanged("DATA_ATUALIZACAO_ACUMULADO");
					this.OnDATA_ATUALIZACAO_ACUMULADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSUMO_MES_1", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> CONSUMO_MES_1
		{
			get
			{
				return this._CONSUMO_MES_1;
			}
			set
			{
				if ((this._CONSUMO_MES_1 != value))
				{
					this.OnCONSUMO_MES_1Changing(value);
					this.SendPropertyChanging();
					this._CONSUMO_MES_1 = value;
					this.SendPropertyChanged("CONSUMO_MES_1");
					this.OnCONSUMO_MES_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSUMO_MES_2", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> CONSUMO_MES_2
		{
			get
			{
				return this._CONSUMO_MES_2;
			}
			set
			{
				if ((this._CONSUMO_MES_2 != value))
				{
					this.OnCONSUMO_MES_2Changing(value);
					this.SendPropertyChanging();
					this._CONSUMO_MES_2 = value;
					this.SendPropertyChanged("CONSUMO_MES_2");
					this.OnCONSUMO_MES_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSUMO_MES_3", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> CONSUMO_MES_3
		{
			get
			{
				return this._CONSUMO_MES_3;
			}
			set
			{
				if ((this._CONSUMO_MES_3 != value))
				{
					this.OnCONSUMO_MES_3Changing(value);
					this.SendPropertyChanging();
					this._CONSUMO_MES_3 = value;
					this.SendPropertyChanged("CONSUMO_MES_3");
					this.OnCONSUMO_MES_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSUMO_MES_4", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> CONSUMO_MES_4
		{
			get
			{
				return this._CONSUMO_MES_4;
			}
			set
			{
				if ((this._CONSUMO_MES_4 != value))
				{
					this.OnCONSUMO_MES_4Changing(value);
					this.SendPropertyChanging();
					this._CONSUMO_MES_4 = value;
					this.SendPropertyChanged("CONSUMO_MES_4");
					this.OnCONSUMO_MES_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIS", DbType="Real")]
		public System.Nullable<float> PIS
		{
			get
			{
				return this._PIS;
			}
			set
			{
				if ((this._PIS != value))
				{
					this.OnPISChanging(value);
					this.SendPropertyChanging();
					this._PIS = value;
					this.SendPropertyChanged("PIS");
					this.OnPISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME_PAI", DbType="VarChar(45)")]
		public string NOME_PAI
		{
			get
			{
				return this._NOME_PAI;
			}
			set
			{
				if ((this._NOME_PAI != value))
				{
					this.OnNOME_PAIChanging(value);
					this.SendPropertyChanging();
					this._NOME_PAI = value;
					this.SendPropertyChanged("NOME_PAI");
					this.OnNOME_PAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_mae", DbType="VarChar(45)")]
		public string nome_mae
		{
			get
			{
				return this._nome_mae;
			}
			set
			{
				if ((this._nome_mae != value))
				{
					this.Onnome_maeChanging(value);
					this.SendPropertyChanging();
					this._nome_mae = value;
					this.SendPropertyChanged("nome_mae");
					this.Onnome_maeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CART_TRAB_NUM", DbType="Int")]
		public System.Nullable<int> CART_TRAB_NUM
		{
			get
			{
				return this._CART_TRAB_NUM;
			}
			set
			{
				if ((this._CART_TRAB_NUM != value))
				{
					this.OnCART_TRAB_NUMChanging(value);
					this.SendPropertyChanging();
					this._CART_TRAB_NUM = value;
					this.SendPropertyChanged("CART_TRAB_NUM");
					this.OnCART_TRAB_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CART_TRAB_SERIE", DbType="VarChar(10)")]
		public string CART_TRAB_SERIE
		{
			get
			{
				return this._CART_TRAB_SERIE;
			}
			set
			{
				if ((this._CART_TRAB_SERIE != value))
				{
					this.OnCART_TRAB_SERIEChanging(value);
					this.SendPropertyChanging();
					this._CART_TRAB_SERIE = value;
					this.SendPropertyChanged("CART_TRAB_SERIE");
					this.OnCART_TRAB_SERIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGIME_TRAB", DbType="VarChar(45)")]
		public string REGIME_TRAB
		{
			get
			{
				return this._REGIME_TRAB;
			}
			set
			{
				if ((this._REGIME_TRAB != value))
				{
					this.OnREGIME_TRABChanging(value);
					this.SendPropertyChanging();
					this._REGIME_TRAB = value;
					this.SendPropertyChanged("REGIME_TRAB");
					this.OnREGIME_TRABChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENC_TOTAL", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> VENC_TOTAL
		{
			get
			{
				return this._VENC_TOTAL;
			}
			set
			{
				if ((this._VENC_TOTAL != value))
				{
					this.OnVENC_TOTALChanging(value);
					this.SendPropertyChanging();
					this._VENC_TOTAL = value;
					this.SendPropertyChanged("VENC_TOTAL");
					this.OnVENC_TOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_CIVIL", DbType="VarChar(25)")]
		public string ESTADO_CIVIL
		{
			get
			{
				return this._ESTADO_CIVIL;
			}
			set
			{
				if ((this._ESTADO_CIVIL != value))
				{
					this.OnESTADO_CIVILChanging(value);
					this.SendPropertyChanging();
					this._ESTADO_CIVIL = value;
					this.SendPropertyChanged("ESTADO_CIVIL");
					this.OnESTADO_CIVILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_DEPENDENTES", DbType="Int")]
		public System.Nullable<int> NUM_DEPENDENTES
		{
			get
			{
				return this._NUM_DEPENDENTES;
			}
			set
			{
				if ((this._NUM_DEPENDENTES != value))
				{
					this.OnNUM_DEPENDENTESChanging(value);
					this.SendPropertyChanging();
					this._NUM_DEPENDENTES = value;
					this.SendPropertyChanged("NUM_DEPENDENTES");
					this.OnNUM_DEPENDENTESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_ADMISSAO", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DATA_ADMISSAO
		{
			get
			{
				return this._DATA_ADMISSAO;
			}
			set
			{
				if ((this._DATA_ADMISSAO != value))
				{
					this.OnDATA_ADMISSAOChanging(value);
					this.SendPropertyChanging();
					this._DATA_ADMISSAO = value;
					this.SendPropertyChanged("DATA_ADMISSAO");
					this.OnDATA_ADMISSAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_DEMISSAO", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DATA_DEMISSAO
		{
			get
			{
				return this._DATA_DEMISSAO;
			}
			set
			{
				if ((this._DATA_DEMISSAO != value))
				{
					this.OnDATA_DEMISSAOChanging(value);
					this.SendPropertyChanging();
					this._DATA_DEMISSAO = value;
					this.SendPropertyChanged("DATA_DEMISSAO");
					this.OnDATA_DEMISSAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIM_CONTRATO", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FIM_CONTRATO
		{
			get
			{
				return this._FIM_CONTRATO;
			}
			set
			{
				if ((this._FIM_CONTRATO != value))
				{
					this.OnFIM_CONTRATOChanging(value);
					this.SendPropertyChanging();
					this._FIM_CONTRATO = value;
					this.SendPropertyChanged("FIM_CONTRATO");
					this.OnFIM_CONTRATOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRITO", DbType="VarChar(45)")]
		public string DISTRITO
		{
			get
			{
				return this._DISTRITO;
			}
			set
			{
				if ((this._DISTRITO != value))
				{
					this.OnDISTRITOChanging(value);
					this.SendPropertyChanging();
					this._DISTRITO = value;
					this.SendPropertyChanged("DISTRITO");
					this.OnDISTRITOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALDO_DEVEDOR", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> SALDO_DEVEDOR
		{
			get
			{
				return this._SALDO_DEVEDOR;
			}
			set
			{
				if ((this._SALDO_DEVEDOR != value))
				{
					this.OnSALDO_DEVEDORChanging(value);
					this.SendPropertyChanging();
					this._SALDO_DEVEDOR = value;
					this.SendPropertyChanged("SALDO_DEVEDOR");
					this.OnSALDO_DEVEDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALDO_DEVEDOR_FAT", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> SALDO_DEVEDOR_FAT
		{
			get
			{
				return this._SALDO_DEVEDOR_FAT;
			}
			set
			{
				if ((this._SALDO_DEVEDOR_FAT != value))
				{
					this.OnSALDO_DEVEDOR_FATChanging(value);
					this.SendPropertyChanging();
					this._SALDO_DEVEDOR_FAT = value;
					this.SendPropertyChanged("SALDO_DEVEDOR_FAT");
					this.OnSALDO_DEVEDOR_FATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SETOR_ID", DbType="Int")]
		public System.Nullable<int> SETOR_ID
		{
			get
			{
				return this._SETOR_ID;
			}
			set
			{
				if ((this._SETOR_ID != value))
				{
					this.OnSETOR_IDChanging(value);
					this.SendPropertyChanging();
					this._SETOR_ID = value;
					this.SendPropertyChanged("SETOR_ID");
					this.OnSETOR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARTAO_BEM_ESTAR", DbType="Char(1) NOT NULL")]
		public char CARTAO_BEM_ESTAR
		{
			get
			{
				return this._CARTAO_BEM_ESTAR;
			}
			set
			{
				if ((this._CARTAO_BEM_ESTAR != value))
				{
					this.OnCARTAO_BEM_ESTARChanging(value);
					this.SendPropertyChanging();
					this._CARTAO_BEM_ESTAR = value;
					this.SendPropertyChanged("CARTAO_BEM_ESTAR");
					this.OnCARTAO_BEM_ESTARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENVIA_SMS", DbType="Char(1)")]
		public System.Nullable<char> ENVIA_SMS
		{
			get
			{
				return this._ENVIA_SMS;
			}
			set
			{
				if ((this._ENVIA_SMS != value))
				{
					this.OnENVIA_SMSChanging(value);
					this.SendPropertyChanging();
					this._ENVIA_SMS = value;
					this.SendPropertyChanged("ENVIA_SMS");
					this.OnENVIA_SMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAO_GERA_CARTAO_TITULAR", DbType="Char(1)")]
		public System.Nullable<char> NAO_GERA_CARTAO_TITULAR
		{
			get
			{
				return this._NAO_GERA_CARTAO_TITULAR;
			}
			set
			{
				if ((this._NAO_GERA_CARTAO_TITULAR != value))
				{
					this.OnNAO_GERA_CARTAO_TITULARChanging(value);
					this.SendPropertyChanging();
					this._NAO_GERA_CARTAO_TITULAR = value;
					this.SendPropertyChanged("NAO_GERA_CARTAO_TITULAR");
					this.OnNAO_GERA_CARTAO_TITULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXA_SERVICO_CANTINA", DbType="Char(1)")]
		public System.Nullable<char> TAXA_SERVICO_CANTINA
		{
			get
			{
				return this._TAXA_SERVICO_CANTINA;
			}
			set
			{
				if ((this._TAXA_SERVICO_CANTINA != value))
				{
					this.OnTAXA_SERVICO_CANTINAChanging(value);
					this.SendPropertyChanging();
					this._TAXA_SERVICO_CANTINA = value;
					this.SendPropertyChanged("TAXA_SERVICO_CANTINA");
					this.OnTAXA_SERVICO_CANTINAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SENHA_CANTINEX", DbType="VarChar(40)")]
		public string SENHA_CANTINEX
		{
			get
			{
				return this._SENHA_CANTINEX;
			}
			set
			{
				if ((this._SENHA_CANTINEX != value))
				{
					this.OnSENHA_CANTINEXChanging(value);
					this.SendPropertyChanging();
					this._SENHA_CANTINEX = value;
					this.SendPropertyChanged("SENHA_CANTINEX");
					this.OnSENHA_CANTINEXChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
